### ISSUE TITLE
How do I edit DLC metadata? I need to tag DLCs as Windows games rather than Mac

### ISSUE THREAD

**Issue by ienzo** [tralph3/Steam-Metadata-Editor#14]
I tried installing Assassin's Creed Unity last month. I got the following error message: `Failed to request product key from Steam, please try again in a few minutes`. According to [this thread](https://github.com/ValveSoftware/Proton/issues/190), this bug is due to the file appinfo.vdf which miscategorizes Ubisoft DLCs as being Mac games and tries to fetch a Mac key. I already have a Windows key for AC Unity, so the advice in [this other thread](https://www.reddit.com/r/linux_gaming/comments/olyezd/assassins_creed_unity_failed_to_request_product/) doesn't work. People in the first thread were able to get AC 2 to work by modifying appinfo.vdf.

Now I downloaded the [Steam Metadata Editor](https://github.com/tralph3/Steam-Metadata-Editor) which can read and modify appinfo.vdf, but it apparently can't modify DLC metadata, which I need to recategorize the DLCs of AC Unity to be Windows and not Mac. I do not know how else to edit appinfo.vdf. If you know a way to edit DLCs on appinfo.vdf using this app, please let me know.

**Comment by tralph3** [comment]
Ok so apparently the fix is to hide the DLC. Currently, you can't hide applications from the GUI itself, but that's what the JSON is for!

Firstly, go to SteamDB and get the AppID for the DLC you want to hide. Then, run this command (without the brackets, of course):

    steammetadataeditor -e [AppID]

This should export the data for the DLC. Now, open the `modifications.json` file located in `~/.local/share/Steam-Metadata-Editor/config/modifications.json`.

Find the entry for the DLC by looking at the AppID. Look for the `modified` key, and inside it, look for the `type` key. You need to change it to `hidden_DLC`:

<img src="https://i.imgur.com/4MWKTLM.png"/>

Once that's done, save the file and run this command:

    steammetadataeditor -s

To apply the changes to the `appinfo.vdf` file. Alternatively, you can open the GUI and click the `Save` button, should work as well.

Let me know if it worked.

**Comment by ienzo** [comment]
Thank you! I will try this.

**Comment by ienzo** [comment]
It works! Thanks.

**Comment by tralph3** [comment]
Glad to hear.
