### ISSUE TITLE
how do i run this on windows the instructions are very unclear

### ISSUE THREAD

**Issue by squid-desert** [tralph3/Steam-Metadata-Editor#19]

**Comment by tralph3** [comment]
You simply need to download Python3. Go to their download page, and install it. Through the installation, you will see a checkmark for "Tk/Tcl". Mark it. After that simply download the program, and run it with Python.

However you may be better suited by [Steam Edit](https://steamedit.tg-software.com/) since this tool is primarily for Linux.

**Comment by mirh** [comment]
It would help greatly for Windows folks if you could add the .py extension to the script.

**Comment by tralph3** [comment]
The reason it's not there is because the script is directly dropped into the "executables" directory on Linux. So if it were there, you would need to type it to call the command. I understand how this is cumbersome on Windows, since that way you could double click on it and launch the interpreter.

The solution I guess would be to drop the program somewhere else, and simply have a bash script that calls it.

I'll see what I can do.

**Comment by tralph3** [comment]
This should be fixed now.

**Comment by mirh** [comment]
Uh, I see where you were coming from... And I couldn't really think to anything better than that, short of terminals having some sort of wildcard whitelist for executable extensions (i.e. windows' behavior of guessing it). 
The folder tree is a bit odd though. You have a couple of "administrative" files in the root, and then a src folder with basically just a single file sinde (which is actually the most important of them all?)

**Comment by tralph3** [comment]
That is kinda standard. You have the source code in a `src` folder. The `img` folder is also there since it's needed for the program to work. Everything outside of it is complementary. The desktop file, utility scripts, project settings, maybe a Dockerfile, etc.

None of that is needed for the program to work.
